name: Trigger DigitalOcean Rebuild

on:
  push:
    branches:
      - main # ou o branch que quiser monitorar

jobs:
  rebuild-app:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger DigitalOcean App Rebuild
        env:
          DO_APP_ID: ${{ secrets.DO_APP_ID }}
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          curl -X POST "https://api.digitalocean.com/v2/apps/$DO_APP_ID/deployments" \
            -H "Authorization: Bearer $DO_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"force_rebuild": true}'
